### ISSUE TITLE
Can this be done for Copying Tweet Links?

### ISSUE THREAD

**Issue by Jgr9** [luciomartinez/tweet-pure-links#9]
Can something like this be done for copying links to tweets?

When I click the button to "Copy link to Tweet" of any specific Tweet, it adds "?s=20" to the end of it, which takes me to a view I don't frickin' want.  Can you cut that off of it, so it takes me to the tweet with all replies expanded, as it should (and used to)?

**Comment by luciomartinez** [comment]
Hey thanks for bringing this suggestion! 👏 

To be honest, when it comes to clipboard things get tricky due [privacy concerns](https://www.w3.org/TR/clipboard-apis/#privacy-async). The [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) might be not available to be accessed/modified from the plugin.

However, I'd like to see this feature working since is very clear and helpful. I'll try to see whether it is something feasible or not and let you know. In the meantime, please share your setup so that I can test with a similar environment.

Which browser(s) are you using? Would you like to have this feature in the [browser extension](https://github.com/luciomartinez/tweet-pure-links/wiki/Browser-Extension-Guide) or [user script](https://github.com/luciomartinez/tweet-pure-links/wiki/User-Script-Guide)?

**Comment by Jgr9** [comment]
Firefox 79 64-bit (public release) (Windows 10)

An extension/add-on would be simpler for more users.

**Comment by luciomartinez** [comment]
Thanks for sharing your details!

After a bit of work on this feature I have got an initial implementation (#11) that seems to do the job.

There's a bit of more testing left in order to verify that the new feature doesn't break the existing one. In case you feel confortable doing early testing, I'd appreciate your input on it. Otherwise you'll hear from me soon.

**Comment by Jgr9** [comment]
Is there a way I can get this and install it?

**Comment by luciomartinez** [comment]
It would be great if you can install it from the source code in order to test it before submitting it into the marketplace. Following is the instructions. Feel free to skip it in case the instructions are rather difficult (anyways I must test other browsers so can do Firefox too).

**Download**

In order to test the extension the first thing to do is download it to your computer. The extension is under the [`feature/copy-link-to-tweet`](https://github.com/luciomartinez/tweet-pure-links/tree/feature/copy-link-to-tweet) branch so [download it](https://github.com/luciomartinez/tweet-pure-links/archive/feature/copy-link-to-tweet.zip) as a ZIP.

**Install**

Once you've got the extension files on your computer now is time to install it. You can get it installed following the [Trying it out](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#Trying_it_out) section from the Mozilla Add-ons tutorial. Let me resume the main bits here:

1. Open Mozilla and go to `about:debugging#/runtime/this-firefox`
2. Click "Load Temporary Add-on"
3. Then go to the directory of the repo and select the script `user-script/tweet-pure-links.user.js`

Now you will have the extension installed and ready to be tested.

**Last steps**

I have tested it on Safari (works!). I'll test on Chrome shortly. Let me know the results in case you manage to do it on Firefox. After the testing phase I'll proceed to submit it on the marketplace so you can install it easily from there (and remove the testing version if existing).

**Comment by Jgr9** [comment]
"does not contain a valid manifest" ?

I copied the manifest.json from browser-extension to user-script and got it loaded, but it still has ?s=20 at the end of my copied link.  (using Copy link to Tweet from the bottom right menu.)  Maybe it's the manifest from the old version? idk.

**Comment by luciomartinez** [comment]
Thanks for giving it a try!

Sorry for that misstep. There were a couple of steps more missing but I compressed them all into a script to make it easier. After download:

1. `cd browser-extension`
2. `chmod +x build_unpacked.sh`
3. `./build_unpacked.sh`

It will generate the `browser-extension/unpacked` directory that can be imported from the Firefox Add-on panel.

However, it seems there is an issue somewhere as I am testing with Chrome and is not working neither 😞 
Likely due lack of permissions since it should ask for clipboard privileges but is not happening. Let me investigate a bit further  so you don't lose time on it.

**Comment by Jgr9** [comment]
I don't know how to do that stuff really anyways, so I probably won't be much help... unless it's "built".

**Comment by luciomartinez** [comment]
Sorry but unfortunately the feature never worked out. Therefore, I'm closing this issue. Thanks again for your contribution!
